version: 2.1
executors:
  builder:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    executor: builder

    environment:
      JVM_OPTS: -Xmx16g
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "b2:c4:41:19:fd:21:1f:f4:93:5d:25:f5:f7:4c:e0:f5"

      - checkout

      - run: git submodule sync

      - run: git submodule update --init

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew website

#      - persist_to_workspace:
#          root: build
#          paths:
#            - distributions

      - run: ./.circleci/publish.sh

workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages

