version: '3.8'

services:
    nineml_server:
      image: httpd:2.4
      container_name: nineml
      ports:
        - 8285:80
      working_dir: /src
      volumes:
        - ../build/website:/usr/local/apache2/htdocs
      stdin_open: true
      tty: true
      networks:
        - external_nineml

networks:
  external_nineml: {}
